export const tmPresets = [
  {
    id: 'tm-1-plus-1',
    type: 'tm',
    title: '1 + 1 = 10',
    description: 'Binary: 1 + 1 = 10 (2 in decimal).',
    states: [
      { id: 'q0', label: 'q0', start: true, x: 80, y: 200 },
      { id: 'q1', label: 'q1', x: 180, y: 120 },
      { id: 'q2', label: 'q2', x: 180, y: 280 },
      { id: 'q3', label: 'q3', x: 320, y: 200 },
      { id: 'q_accept', label: 'q_accept', accept: true, x: 440, y: 200 },
    ],
    alphabet: ['0', '1', '+'],
    sampleInputs: ['1+1', '10+1', '101+11'],
    transitionTable: [
      { state: 'q0', read: '0', write: '0', move: 'R', nextState: 'q1' },
      { state: 'q0', read: '1', write: '1', move: 'R', nextState: 'q1' },
      { state: 'q1', read: '0', write: '0', move: 'R', nextState: 'q1' },
      { state: 'q1', read: '1', write: '1', move: 'R', nextState: 'q1' },
      { state: 'q1', read: '+', write: '+', move: 'R', nextState: 'q2' },
      { state: 'q2', read: '0', write: '0', move: 'R', nextState: 'q2' },
      { state: 'q2', read: '1', write: '1', move: 'R', nextState: 'q2' },
      { state: 'q2', read: '_', write: '_', move: 'L', nextState: 'q3' },
      { state: 'q3', read: '0', write: '0', move: 'L', nextState: 'q3' },
      { state: 'q3', read: '+', write: '+', move: 'L', nextState: 'q_accept' },
    ],
  },
  {
    id: 'tm-10-plus-1',
    type: 'tm',
    title: '10 + 1 = 11',
    description: 'Binary: 10 + 1 = 11 (3 in decimal).',
    states: [
      { id: 'q0', label: 'q0', start: true, x: 80, y: 200 },
      { id: 'q1', label: 'q1', x: 180, y: 120 },
      { id: 'q2', label: 'q2', x: 180, y: 280 },
      { id: 'q3', label: 'q3', x: 320, y: 200 },
      { id: 'q_accept', label: 'q_accept', accept: true, x: 440, y: 200 },
    ],
    alphabet: ['0', '1', '+'],
    sampleInputs: ['10+1', '1+1', '101+11'],
    transitionTable: [
      { state: 'q0', read: '0', write: '0', move: 'R', nextState: 'q1' },
      { state: 'q0', read: '1', write: '1', move: 'R', nextState: 'q1' },
      { state: 'q1', read: '0', write: '0', move: 'R', nextState: 'q1' },
      { state: 'q1', read: '1', write: '1', move: 'R', nextState: 'q1' },
      { state: 'q1', read: '+', write: '+', move: 'R', nextState: 'q2' },
      { state: 'q2', read: '0', write: '0', move: 'R', nextState: 'q2' },
      { state: 'q2', read: '1', write: '1', move: 'R', nextState: 'q2' },
      { state: 'q2', read: '_', write: '_', move: 'L', nextState: 'q3' },
      { state: 'q3', read: '0', write: '0', move: 'L', nextState: 'q3' },
      { state: 'q3', read: '+', write: '+', move: 'L', nextState: 'q_accept' },
    ],
  },
  {
    id: 'tm-101-plus-11',
    type: 'tm',
    title: '101 + 11 = 1000',
    description: 'Binary: 101 + 11 = 1000 (carry propagation example).',
    states: [
      { id: 'q0', label: 'q0', start: true, x: 80, y: 200 },
      { id: 'q1', label: 'q1', x: 180, y: 120 },
      { id: 'q2', label: 'q2', x: 180, y: 280 },
      { id: 'q3', label: 'q3', x: 320, y: 200 },
      { id: 'q_accept', label: 'q_accept', accept: true, x: 440, y: 200 },
    ],
    alphabet: ['0', '1', '+'],
    sampleInputs: ['101+11', '1+1', '10+1'],
    transitionTable: [
      { state: 'q0', read: '0', write: '0', move: 'R', nextState: 'q1' },
      { state: 'q0', read: '1', write: '1', move: 'R', nextState: 'q1' },
      { state: 'q1', read: '0', write: '0', move: 'R', nextState: 'q1' },
      { state: 'q1', read: '1', write: '1', move: 'R', nextState: 'q1' },
      { state: 'q1', read: '+', write: '+', move: 'R', nextState: 'q2' },
      { state: 'q2', read: '0', write: '0', move: 'R', nextState: 'q2' },
      { state: 'q2', read: '1', write: '1', move: 'R', nextState: 'q2' },
      { state: 'q2', read: '_', write: '_', move: 'L', nextState: 'q3' },
      { state: 'q3', read: '0', write: '0', move: 'L', nextState: 'q3' },
      { state: 'q3', read: '+', write: '+', move: 'L', nextState: 'q_accept' },
    ],
  },
];
